cats_99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only:[:show, :index, :new, :create, :update, :edit]
end

cats_99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats_99/app/models/cat.rb
class Cat < ApplicationRecord

  validates :birth_date, :color, :name, :description, presence: true
  validates :sex, presence:true, inclusion: { in: %w(M F)}

  def self.colors
    ['white','black','brown','orange','yellow','naked', 'teal', 'indigo',
      'lavender', 'sky blue', 'maroon', 'grey', 'magenta', 'violet'
    ]
  end

end

cats_99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

cats_99/app/controllers/cats_controller.rb
class CatsController < ApplicationController


  def index
    @cats = Cat.all
    render :index
  end

  def show
    begin
      @cat = Cat.find(params[:id])
      render :show
    rescue
      render plain: 'Cannot be found'
    end
  end

  def new
    @colors = Cat.colors
    @cat = nil
    render :new
  end

  def create
    render json: cat_params
  end

  def edit
    @colors = Cat.colors
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      render json: @cat
    else
      render json: @cat.errors.full_messages, status: :unprocessible_entity
    end
  end


  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

cats_99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats_99/app/helpers/cats_helper.rb
module CatsHelper
end

cats_99/app/views/cats/edit.html.erb
<!-- @cat -->
<form action= "/cats/<%=@cat.id%>" method="post">
<!-- <form action = "<%#=cat_url(@cat)%>" -->
  <input type="hidden" name="_method" value="PATCH">

  <label for="cat_name">Name</label>
  <input name="cat[name]" id="cat_name" type="text" value="<%= @cat.name %>">
  <br>

  <label for="birth_date">Birth Date</label>
  <input name="cat[birth_date]" id="birth_date" type="date" value="<%= @cat.birth_date %>">
  <br>



  <label for="cat_coat_color"> Coat Color </label>
  <select name = "cat[color]" id= 'cat_coat_color'>
    <option value="--Please Select--" disabled></option>
    <% @colors.each do |color| %>
      <option value = "<%= color %>" <%= color == @cat.color ? "selected" : "" %> >
        <%= color.capitalize %>
      </option>
    <% end %>
  </select>

  <br>

  <label> Gender: </label>
  <label> Male </label>
  <input type="radio" name="cat[sex]" value="M" <%= "M" == @cat.sex ? "checked" : "" %>>
  <label> Female </label>
  <input type="radio" name="cat[sex]" value="F" <%= "F" == @cat.sex ? "checked" : "" %>>
  <br>

  <label for="description"> Description </label>
  <p>
    <textarea name="cat[description]" id = "description">
      <%= @cat.description %>
    </textarea>
  </p>

  <input type="submit" value="Edit Cat">
</form>

cats_99/app/views/cats/index.html.erb
<!-- @cats -->

<table>
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Sex</th>
    <th>Color</th>
    <th>description</th>
  </tr>

  <% @cats.each do |cat| %>
    <tr>
      <td><%= cat.name %></td>
      <td><%= cat.birth_date %></td>
      <td><%= cat.sex %></td>
      <td><%= cat.color %></td>
      <td><%= cat.description %></td>
    </tr>
  <% end %>
</table>

cats_99/app/views/cats/new.html.erb
<form  action="/cats" method="post">
  <label for="cat_name">Name</label>
  <input name="cat[name]" id="cat_name" type="text">
  <br>

  <label for="birth_date">Birth Date</label>
  <input name="cat[birth_date]" id="birth_date" type="date">
  <br>



  <label for="cat_coat_color"> Coat Color </label>
  <select name = "cat[color]" id= 'cat_coat_color'>
    <option value="--Please Select--" disabled selected></option>
    <% @colors.each do |color| %>
      <option value=" <%= color %> "> <%= color.capitalize %> </option>
    <% end %>
  </select>

  <br>

  <label> Gender: </label>
  <label> Male </label>
  <input type="radio" name="cat[sex]" value="M">
  <label> Female </label>
  <input type="radio" name="cat[sex]" value="F">
  <br>

  <label for="description"> Description </label>
  <p>
    <textarea name="cat[description]" id = "description"></textarea>
  </p>

  <input type="submit" value="Add Cat">
</form>

<%= render "form", cat: @cat, action: :new %>

cats_99/app/views/cats/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Sex</th>
    <th>Color</th>
    <th>description</th>
  </tr>

  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

cats_99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>